### ISSUE TITLE
Custom Event Manager Dies

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/sockets#27]
The custom event manager sometimes dies with `stepManager: C 4`

**Comment by andrewthad** [comment]
Fixed by a8056a390a5657a563e272e2dead859fc9a4ee15

cc @chessai

**Comment by chessai** [comment]
i'll try this out and confirm that it works

**Comment by chessai** [comment]
no, i updated to that commit and still get C 4. however, it happened right after the push this time.

**Comment by andrewthad** [comment]
Did you update both the server and the client?

**Comment by chessai** [comment]
i did update them both.

**Comment by chessai** [comment]
let me check to make sure.

**Comment by chessai** [comment]
sockets is on:

```
        rev = "a8056a390a5657a563e272e2dead859fc9a4ee15";
        sha256 = "0bk5vbcglcjkpw30rsd3iaj7zp2lrqp13q4v1m8d55wmsnmp202d";
```

**Comment by chessai** [comment]
i was mistaken. i looked at the wrong systemd error. it is actually segfaulting.

**Comment by andrewthad** [comment]
This was determined to be an error in `rotera`. Closing.
